server.port: 8085
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/video_game_shop
    username: video-game
    password: video-game